### ISSUE TITLE
 java.lang.ClassCastException when casting JSONArray to JSONObject

### ISSUE THREAD

**Issue by mrksbrg** [wogscpar/SZZUnleashed#11]
The "issues" subfolder is created, but it's empty.

Here is the stack trace:

```
[main] INFO Main - Checking available processors...
[main] INFO Main - Found 8 processes!
Exception in thread "main" java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to org.json.simple.JSONObject
        at diff.SimplePartition.splitJSON(SimplePartition.java:52)
        at diff.SimplePartition.splitFile(SimplePartition.java:121)
        at Main.main(Main.java:44)
```

**Comment by mrksbrg** [comment]
This happens when you pass the expected output file instead of the path_to_issue_list.json. The example file is attached. Perhaps add an early file format check?

[fix_and_introducers_pairs.zip](https://github.com/wogscpar/SZZUnleashed/files/2823334/fix_and_introducers_pairs.zip)

**Comment by wogscpar** [comment]
I've uploaded some [examples](https://github.com/wogscpar/SZZUnleashed/tree/master/examples/data) where you can find correctly produced data @mrksbrg .
