### ISSUE TITLE
FileNotFoundError in git_log_to_array.py 

### ISSUE THREAD

**Issue by mrksbrg** [wogscpar/SZZUnleashed#3]
FileNotFoundError exception in git_log_to_array.py, see below.

Cloned jenkins to C:\Code\jenkins and provided absolute path to script. Tried a few variations of separators in file path. Not sure which file the system is looking for.

```
C:\Code\SZZUnleashed\fetch_jira_bugs>python git_log_to_array.py --repo-path C:/Code/jenkins
Traceback (most recent call last):
  File "git_log_to_array.py", line 43, in <module>
    git_log_to_json(init_hash, path_to_repo)
  File "git_log_to_array.py", line 14, in git_log_to_json
    stdout=subprocess.PIPE).stdout.decode('ascii').split()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by wogscpar** [comment]
This could be a result of using Windows(not sure). What shell are you using?

**Comment by mrksbrg** [comment]
This was tested using the standard Windows Command Processor, a.k.a. cmd.exe. (Version 10.0.17134.523)

**Comment by wogscpar** [comment]
Try to pass **C:\\\\Code\\\\jenkins** instead of **C:\Code\jenkins**.

**Comment by mrksbrg** [comment]
No need for '\\'. I cannot repeat the issue any longer. I probably provided some faulty argument before. This issue can be closed - but I'll post another one now.

**Comment by mrksbrg** [comment]
Tried that already, no difference.

**Comment by wogscpar** [comment]
Even though it's a security issue to do this, can you try to change lines 12-13 to
```python
 hashes = subprocess.run(['git', 'rev-list', init_hash], shell=true, cwd=path_to_repo,
stdout=subprocess.PIPE).stdout.decode('ascii').split()
```
I can't do the test myself since I do not have a PC running Windows at the moment.

**Comment by mrksbrg** [comment]
Progress I believe.

`hashes = subprocess.run(['git', 'rev-list', init_hash], shell=True, cwd=path_to_repo, 
	stdout=subprocess.PIPE).stdout.decode('ascii').split()`

gave me:

`C:\Code\SZZUnleashed\fetch_jira_bugs>python git_log_to_array.py --repo-path C:\Code\jenkins
Traceback (most recent call last):
  File "git_log_to_array.py", line 45, in <module>
    git_log_to_json(init_hash, path_to_repo)
  File "git_log_to_array.py", line 14, in git_log_to_json
    stdout=subprocess.PIPE).stdout.decode('ascii').split()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 971, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable`

However, I get the same TypeError no matter what path I provide, e.g., 
`python git_log_to_array.py --repo-path dummypath`

I'm supposed to provide the path to the root dir of the jenkins repo, right?

**Comment by wogscpar** [comment]
As mentioned in this [thread](https://stackoverflow.com/questions/4965175/make-subprocess-find-git-executable-on-windows/10555130#10555130), one can try to resolve where git is located. I don't think this issue has something with the path to the repository but the executable itself. Could you try to add that to the script?
