### ISSUE TITLE
ClassCastException in GitParser.java:342

### ISSUE THREAD

**Issue by mrksbrg** [wogscpar/SZZUnleashed#4]
Successfully built szz_find_bug_introducers-0.1.jar with gradle. The res1000.json file appears to be populated with correct data. 

Not sure if it is related, an also not sure what the purpose of the file results\result0\commits.json is, but it is missing and a FileNotFoundException is thrown.

If this is not a bug, then the instructions need to be updated to explain what needs to be present before running the jar file.

Output and stack trace:
```
java -jar szz_find_bug_introducers-0.1.jar -i C:\Code\SZZUnleashed\fetch_jira_bugs\issues\res1000.json -r C:\Code\jenkins
[main] INFO Main - Checking available processors...
[main] INFO Main - Found 8 processes!
[Thread-0] INFO parser.GitParserThread - Started process...
Exception in thread "Thread-0" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at parser.GitParser.readBugFixCommits(GitParser.java:342)
        at parser.GitParserThread.run(GitParserThread.java:94)
[Thread-1] INFO parser.GitParserThread - Started process...
Exception in thread "Thread-1" java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Map
        at parser.GitParser.readBugFixCommits(GitParser.java:342)
        at parser.GitParserThread.run(GitParserThread.java:94)
[Thread-2] INFO parser.GitParserThread - Started process...
Exception in thread "Thread-2" java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Map
        at parser.GitParser.readBugFixCommits(GitParser.java:342)
        at parser.GitParserThread.run(GitParserThread.java:94)
[Thread-3] INFO parser.GitParserThread - Started process...
[Thread-4] INFO parser.GitParserThread - Started process...
[Thread-5] INFO parser.GitParserThread - Started process...
[Thread-5] INFO parser.GitParserThread - Found 0 number of commits.
[Thread-5] INFO parser.GitParserThread - Checking each commits diff...
[Thread-5] INFO parser.GitParserThread - Parsing difflines for all found commits.
[Thread-5] INFO parser.GitParserThread - Saving parsed commits to file
Exception in thread "Thread-4" java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.Map
        at parser.GitParser.readBugFixCommits(GitParser.java:342)
        at parser.GitParserThread.run(GitParserThread.java:94)
[Thread-5] INFO parser.GitParserThread - Building line mapping graph.
[Thread-6] INFO parser.GitParserThread - Started process...
[Thread-5] INFO parser.GitParserThread - Saving results to file
[Thread-6] INFO parser.GitParserThread - Found 0 number of commits.
[Thread-6] INFO parser.GitParserThread - Checking each commits diff...
[Thread-5] INFO parser.GitParserThread - Trying to find potential bug introducing commits...
[Thread-6] INFO parser.GitParserThread - Parsing difflines for all found commits.
[Thread-6] INFO parser.GitParserThread - Saving parsed commits to file
[Thread-5] INFO parser.GitParserThread - Saving found bug introducing commits...
[Thread-7] INFO parser.GitParserThread - Started process...
[Thread-6] INFO parser.GitParserThread - Building line mapping graph.
[Thread-7] INFO parser.GitParserThread - Found 0 number of commits.
[Thread-6] INFO parser.GitParserThread - Saving results to file
[Thread-7] INFO parser.GitParserThread - Checking each commits diff...
[Thread-7] INFO parser.GitParserThread - Parsing difflines for all found commits.
[Thread-6] INFO parser.GitParserThread - Trying to find potential bug introducing commits...
[Thread-7] INFO parser.GitParserThread - Saving parsed commits to file
[Thread-6] INFO parser.GitParserThread - Saving found bug introducing commits...
[Thread-7] INFO parser.GitParserThread - Building line mapping graph.
[Thread-7] INFO parser.GitParserThread - Saving results to file
[Thread-7] INFO parser.GitParserThread - Trying to find potential bug introducing commits...
[Thread-7] INFO parser.GitParserThread - Saving found bug introducing commits...
Exception in thread "Thread-3" java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.util.Map
        at parser.GitParser.readBugFixCommits(GitParser.java:342)
        at parser.GitParserThread.run(GitParserThread.java:94)
java.io.FileNotFoundException: results\result0\commits.json (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at diff.SimplePartition.mergeFiles(SimplePartition.java:140)
        at Main.main(Main.java:65)
java.io.FileNotFoundException: results\result1\commits.json (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at diff.SimplePartition.mergeFiles(SimplePartition.java:140)
        at Main.main(Main.java:65)
java.io.FileNotFoundException: results\result2\commits.json (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at diff.SimplePartition.mergeFiles(SimplePartition.java:140)
        at Main.main(Main.java:65)
java.io.FileNotFoundException: results\result3\commits.json (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at diff.SimplePartition.mergeFiles(SimplePartition.java:140)
        at Main.main(Main.java:65)
java.io.FileNotFoundException: results\result4\commits.json (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at diff.SimplePartition.mergeFiles(SimplePartition.java:140)
        at Main.main(Main.java:65)
```

**Comment by wogscpar** [comment]
This is not a bug so I will update the readme properly. The issue path should point to a path where a **issue_list.json** is stored and not to where the res1000.json are stored. 

java -jar ./build/libs/szz_find_bug_introducers-0.1.jar -i <path_to_algorithm>/SZZUnleashed/fetch_jira_bugs -r <path_to_local_copy_of_repo>/jenkins

This is a command. The **issue_list.json** file is in the fetch_jira_bugs directory and is created by the find_bug_fixes.py script. The local copy of the repository that is analyzed is where the repository was cloned.

**Comment by mrksbrg** [comment]
I suppose some previous step didn't generate the required file then, since I have no **issue_list.json**. Is **fix_and_introducers_pairs.json** supposed to contain the very final results?

Perhaps we could add some descriptive error messages when things are not working out as expected?

**Comment by wogscpar** [comment]
Yes, the **fix_and_introducers_pairs.json** will include all pairs where the first in each pair is the fix and the other is the bug introducing commit.

Maybe. We could try to add a check to be sure that a **issue_list.json** has been generated properly in the **find_bug_fixes.py** script.
